# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outoftreemodule',
            name='added_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outoftreemodule',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='outoftreemodule',
            name='repo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outoftreemodule',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
