# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootlist', '0002_auto_20170913_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='outoftreemodule',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
