# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootlist', '0003_outoftreemodule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='outoftreemodule',
            name='last_commit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
