# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootlist', '0004_outoftreemodule_last_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='outoftreemodule',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='outoftreemodule',
            name='copyright_owner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='outoftreemodule',
            name='dependencies',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='outoftreemodule',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='outoftreemodule',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
