# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootlist', '0005_auto_20170920_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outoftreemodule',
            name='dependencies',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='outoftreemodule',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
