# Generated by Django 2.1 on 2018-09-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ootlist', '0008_outoftreemodule_body_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packageversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_name', models.CharField(max_length=500)),
                ('gr_version_string', models.CharField(max_length=500)),
            ],
        ),
    ]
